Reserve rdatas for WALing tid tree leaf items
Inserting a large number of tids into the tid tree at once may cause
zsbt_wal_log_tidleaf_items() to be called with more than
XLR_NORMAL_RDATAS number of tid items. This leads to:
ERROR: "too much WAL data"
when XLogRegisterBufData() is called from within
zsbt_wal_log_tidleaf_items().

To remedy this situation ensure that there is enough rdatas allocated
for all of the items and for any associated undo_op.